awsdocs/amazon-cloudwatch-user-guide

- doc_source/aws-namespaces.md
Description of changes: Adds AWS Glue to CloudWatch namespaces documentation
> Adding AWS Glue namespace to CloudWatch namespaces

- doc_source/CloudWatch-Agent-custom-metrics-collectd.md
The document states the possible choices for `collectd_security_level` are: `None, Sign, Encrypt`, while these values actually do not pass JSON schema validation and result errors.
The correct choices should be: `none, sign, encrypt`.
> Fix possible choices for collectd_security_level

- doc_source/AlarmThatSendsEmail.md
Add additional alarm example when last data point is breaching and the rest of the data is missing. This is a critical edge case that isn't covered in the examples given, and is unintuitive since it's treated differently than other cases of breaching and missing data.
Added an additional row to the table of examples of how missing data is evaluated. Also added a sentence explaining the reason for the alarm state in the new example.
> Add additional alarm example for missing data

- doc_source/CloudWatch-Agent-procstat-process-metrics.md
The _pattern_ example repeats `exe` as the name of the key when it should be `pattern` according to the documentation under the `Configuring the CloudWatch Agent for procstat` H2 header.
> Fix typo in *Configuring with pattern* example

- doc_source/cloudwatch_concepts.md
The definitions of `metric` and `dimension` (along with the relationship between the 2 concepts) is wildly inconsistent within the doc.
For example, the current language includes these statements:
1.  `When you request statistics, the returned data stream is identified by namespace, metric name, dimension, and (optionally) the unit.`
2. `A *dimension* is a name/value pair that uniquely identifies a metric\. `
3. `Whenever you add a unique name/value pair to one of your metrics, you are creating a new variation of that metric`
My concern with (1) is that a metric may involve 0, 1, or multiple metrics.  Also, this introduces a new term (`data stream`) without any definition.  
My concern with (2) is obvious, I think.
My concern with (3) is that it contradicts earlier (appropriate, in my …
> Clarify CloudWatch dimensions

- doc_source/CloudWatch-Agent-Configuration-File-Details.md
Looks like a simple copy/paste error. The `mem` section should not refer to `swap`.
> replace incorrect usage of 'swap' in the 'mem' section

- doc_source/install-CloudWatch-Agent-on-first-instance.md
Currently, the documentation has a requirement on internet access to use CloudWatch logs. With the introduction of the logs VPC Endpoint Interface, you no longer need internet access to use CloudWatch logs on an EC2 instance. This change updates the documentation to reflect that. 
> Update requirements for CloudWatch logs

- doc_source/create-iam-roles-for-cloudwatch-agent.md
"Create IAM Roles to Use with the CloudWatch Agent on Amazon EC2 Instances" was "Creat IAM Roles to Use with the CloudWatch Agent on Amazon EC2 Instances"
- Updated Spelling Mistake: "Create IAM Roles to Use with the CloudWatch Agent on Amazon EC2 Instances" was "Creat IAM Roles to Use with the CloudWatch Agent on Amazon EC2 Instances"
> Updated spelling mistake

- doc_source/search-expression-syntax.md
Hello, dear colleagues! :)
The search syntax does not actually allow a `,` after the `{...}`, and that's not used anywhere else in the page.
Btw, it would be nice if a bit of a cleanup was done on these docs, they are _really_ hard to follow, and I've been doing nothing but dashboards the past two weeks.
> Fix SEARCH examples

- doc_source/GetSingleMetricAllDimensions.md
*Issue #, if available:* Rectified wrong information about CloudWatch data aggregation of metrics across Regions
Since November 2019, you can now use CloudWatch metric math to aggregate and transform metrics from multiple accounts and Regions. Hence, this statement is incorrect: Amazon CloudWatch can't aggregate data across Regions.
Reference: 
https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-cloudwatch-launches-cross-account-cross-region-dashboards/
> Wrong info about aggregating data across Regions using CloudWatch

- doc_source/Container-Insights-metrics-ECS.md
The dimension of ServiceCount metric in ECS/ContainerInsights namespace looks wrong.
> Fix dimension of ServiceCount metric

- doc_source/ContainerInsights-Prometheus-Sample-Workloads-appmesh-envoy.md
- doc_source/ContainerInsights-Prometheus-Sample-Workloads-appmesh.md
AWS App Mesh did a major version upgrade and the existing installation instructions are out of date. Updated the instructions to include the up to date App Mesh Kubernetes controller installation instruction, link to a new sample application and Virtual Node YAML for Envoy logging. 
Also, the new instructions simply refer to the existing links. EKS/AppMesh teams will keep those links up to date for future releases
> Update container insights documentation to use latest appmesh version v1.0.0

- doc_source/Container-Insights-metrics-ECS.md
Fix a typo in the word "utilization" in the file "Container-Insights-metrics-ECS.md"
> fix typo in word "utilization"

- doc_source/ContainerInsights-Prometheus-Setup-configure.md
- doc_source/ContainerInsights-Prometheus-troubleshooting.md
- doc_source/ContainerInsights-Prometheus-viewmetrics.md
Fix the name typo for Kubernetes API Server: https://kubernetes.io/docs/concepts/overview/components/#kube-apiserver
> Fix the name typo for Kubernetes API Server

- doc_source/ContainerInsights-Prometheus-Setup-configure.md
* Prometheus Summary Metric Type is supported in GA.
* CWAgent installation for Kubernetes needs to have the cluster_name and region specified.
> Update Installation Command and Metric Type Note in Tutorial

- doc_source/graph-dynamic-labels.md
*Issue 77, if available:*
At https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/graph-dynamic-labels.html there are curly brackets instead of round brackets in the table for some of the new property dynamic labels:
MetricName
Namespace
Period
Region
Stat
For example in the table is shows: ${PROP('Stat'}}  instead of ${PROP('Stat')}
Made the curly brackets round. 
> Fixed the curly brackets.

- doc_source/Container-Insights-metrics-EKS.md
#70 
Fixes description of the `cluster_failed_node_count` metric. This description in its current form is not particularly useful, because it doesn't allow you to diagnose why this alarm is going off. Based on discussions with an AWS Solutions Architect, this is the condition for this metric.
> Clarify conditions for incrementing cluster_failed_node_count

- doc_source/appinsights-tutorial-dotnet-sql.md
The instructions to add the key pair details under Tags is incorrect. This needs to be done on the parameters section.
Instructions amended at point 4 and 6 to reflect the actual input locations for the key pair details on the cloudformation parameters.
> Key pair section was incorrect

- doc_source/CloudWatch_Synthetics_Canaries_VPC.md
Fix typo of the IAM role name `ec2:DescribeNetworkInterfaces`
added a missing `s`
> fix typo of the IAM role name

- doc_source/CloudWatch_Synthetics_Canaries.md
Added region number and "all".  I think it helps users to know this is available *everywhere* and is not just limited to certain regions that exclude other regions.
> add "all regions" to "Using synthetic monitoring"

- doc_source/appinsights-tutorial-dotnet-sql.md
The underlying link to SampleApp.yml was wrong (the description text is correct)
> fix hyperlink referencing SampleApp.yml

- doc_source/CloudWatch_Synthetics_Canaries_Samples.md
The previous single quotation was the incorrect one causing a lot of the text to be commented out as seen here: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Canaries_Samples.html
N/A
I just changed the quotation to be the actual quote. As when looking in the example a lot of it is commented out because of how this quotation was implemented.
No clue why line 231 has any changes as there is no change here.
> Change to correct single quotation on Canaries sample

- doc_source/CloudWatch_Synthetics_Canaries_Roles.md
Description of changes:
Changed AWSLambdaReadOnlyAccess to AWSLambda_ReadOnlyAccess to reflect correct name for the policy
The policy name was changed on March 1st, please see here for more information:
https://docs.aws.amazon.com/lambda/latest/dg/access-control-identity-based.html
> Changed AWSLambdaReadOnlyAccess to AWSLambda_ReadOnlyAccess

- doc_source/CloudWatch-Agent-custom-metrics-collectd.md
Recently been installing `collectd` an fresh Amazon Linux 2 EC2 and I managed to do it in single step with `amazon-linux-extras`
> Simplify collectd installation on amz2

- doc_source/Container-Insights-setup-logs-FluentBit.md
In the example to filter out the fluent-bit logs the path has the wrong prefix for the container name. I've corrected this from fluent_bit to fluent-bit
> Corrected fluent-bit container name in filter

- doc_source/ContainerInsights-Prometheus-Setup-autodiscovery-ecs.md
In the "Detailed guide for autodiscovery on Amazon ECS clusters" page, the JSON attribute for defining a Task Definition that will be scraped for metrics is incorrect.
It was changed from `sd_task_definition_name_pattern` to `sd_task_definition_arn_pattern`.
> Fix JSON attribute for defining a Task Definition that will be scraped for metrics

- doc_source/deploy-container-insights-ECS-instancelevel.md
This is not noted anywhere in the documentation and runs contrary to some of AWS Security Practices: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html
Therefore it should be documented.
No mention of IMDS in documentation for utilizing CloudWatch Agent with Container Insights to provide instance-level metrics
Added a line dictating it is required. 
> CloudWatch Agent requires access to IMDS

- doc_source/create-cloudwatch-agent-configuration-file-wizard.md
The single box of the command does not work when copied and pasted in Windows PowerShell because of the new-line character. Additionally, the `.exe` file had to be called for execution using the prefix as `.\`. Reach out to parthpg@amazon.com for more details if required.
> Updated Windows commands

- doc_source/Container-Insights-prerequisites.md
This document does not explicitly called out the namespace that is required to be linked with the IAM role having the policy **CloudWatchAgentServerPolicy** attached. Because of that, the users may create such role and the linked service account in a different namespace because the link to the document given here is a generic link that asks the users to create the service account in default namespace. Later in the document, the instructions deploys the CloudWatch and Fluent Bit agents in a namespace called `amazon-cloudwatch`. This mismatch does not grant required permissions to the deployed pods to communicate with the corresponding CloudWatch service on the AWS account. 
This little change will callout this namespace requirements explicitly to avoid any confusion or pain later, which …
> Improved instructions to include namespace

- doc_source/Container-Insights-metrics-EKS.md
n/a
EKS Container Insights metrics incorrectly state that `pod_cpu_utilization_over_pod_limit` tracks CPU utilization that exceeds the pod's limit. In practice, this metric displays the ratio of `pod_cpu_utilization / pod_cpu_limit`, i.e. CPU utilization relative to the pod CPU limits.
Same argument applies to `pod_memory_utilization_over_pod_limit`.
> Fix description of ContainerInsights EKS metrics
